import passport from "passport";
import { Strategy as GoogleStrategy, type Profile } from "passport-google-oauth20";

import { env } from "./env";
import { User } from "../models/User";
import { generateUniqueUsername } from "../utils/username";

const resolveGoogleEmail = (profile: Profile) =>
  profile.emails?.find((item) => item.verified)?.value ??
  profile.emails?.[0]?.value ??
  "";

if (env.google.clientId && env.google.clientSecret) {
  passport.use(
    new GoogleStrategy(
      {
        clientID: env.google.clientId,
        clientSecret: env.google.clientSecret,
        callbackURL: env.google.callbackUrl,
      },
      async (_accessToken, _refreshToken, profile, done) => {
        try {
          const email = resolveGoogleEmail(profile).toLowerCase().trim();

          if (!email) {
            done(new Error("Google did not return an email address."), undefined);
            return;
          }

          let user = await User.findOne({ googleId: profile.id });

          if (user) {
            if (!user.avatarUrl && profile.photos?.[0]?.value) {
              user.avatarUrl = profile.photos[0].value;
              await user.save();
            }

            done(null, user);
            return;
          }

          user = await User.findOne({ email });

          if (user) {
            user.googleId = profile.id;
            user.isVerified = true;

            if (!user.avatarUrl && profile.photos?.[0]?.value) {
              user.avatarUrl = profile.photos[0].value;
            }

            await user.save();
            done(null, user);
            return;
          }

          const generatedUsername = await generateUniqueUsername(
            profile.displayName || email.split("@")[0] || "pulse_user",
          );

          const newUser = await User.create({
            googleId: profile.id,
            email,
            displayName: profile.displayName || email.split("@")[0],
            username: generatedUsername,
            usernameAutoGenerated: true,
            avatarUrl: profile.photos?.[0]?.value ?? "",
            isVerified: true,
            authProvider: "google",
          });

          done(null, newUser);
        } catch (error) {
          done(error as Error, undefined);
        }
      },
    ),
  );
}

passport.serializeUser((user: any, done) => {
  done(null, user._id.toString());
});

passport.deserializeUser(async (id: string, done) => {
  try {
    const user = await User.findById(id);
    done(null, user ?? undefined);
  } catch (error) {
    done(error as Error, undefined);
  }
});

export { passport };
