import { Schema, model, type HydratedDocument, type InferSchemaType, type Types } from "mongoose";

const RefreshTokenSchema = new Schema(
  {
    tokenId: {
      type: String,
      required: true,
    },
    expiresAt: {
      type: Date,
      required: true,
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
    userAgent: String,
    ipAddress: String,
  },
  { _id: false },
);

const PushSubscriptionSchema = new Schema(
  {
    endpoint: {
      type: String,
      required: true,
    },
    expirationTime: Number,
    keys: {
      p256dh: {
        type: String,
        required: true,
      },
      auth: {
        type: String,
        required: true,
      },
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { _id: false },
);

const UserSchema = new Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      minlength: 3,
      maxlength: 24,
    },
    displayName: {
      type: String,
      required: true,
      trim: true,
      maxlength: 40,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    googleId: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
    },
    authProvider: {
      type: String,
      enum: ["local", "google"],
      default: "local",
    },
    isVerified: {
      type: Boolean,
      default: false,
    },
    usernameAutoGenerated: {
      type: Boolean,
      default: false,
    },
    passwordHash: {
      type: String,
      required(this: any) {
        return this.authProvider !== "google";
      },
      select: false,
    },
    bio: {
      type: String,
      default: "",
      maxlength: 180,
    },
    avatarUrl: {
      type: String,
      default: "",
    },
    avatarPublicId: {
      type: String,
      default: "",
    },
    lastSeenAt: {
      type: Date,
      default: Date.now,
    },
    friends: [
      {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    friendRequestsSent: [
      {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    friendRequestsReceived: [
      {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    refreshTokens: [RefreshTokenSchema],
    pushSubscriptions: [PushSubscriptionSchema],
    privacy: {
      lastSeen: {
        type: String,
        enum: ["everyone", "friends", "nobody"],
        default: "friends",
      },
      avatar: {
        type: String,
        enum: ["everyone", "friends", "nobody"],
        default: "everyone",
      },
      stories: {
        type: String,
        enum: ["everyone", "friends", "nobody"],
        default: "friends",
      },
    },
    notificationSettings: {
      pushEnabled: {
        type: Boolean,
        default: true,
      },
      customSound: {
        type: Boolean,
        default: false,
      },
      mutedChats: [
        {
          type: Schema.Types.ObjectId,
          ref: "Chat",
        },
      ],
      mutedChannels: [
        {
          type: Schema.Types.ObjectId,
          ref: "Channel",
        },
      ],
    },
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
    },
    toObject: {
      virtuals: true,
    },
  },
);

UserSchema.virtual("needsUsernameSetup").get(function needsUsernameSetup(this: any) {
  return this.authProvider === "google" && Boolean(this.usernameAutoGenerated);
});

export type IUser = InferSchemaType<typeof UserSchema> & {
  _id: Types.ObjectId;
  needsUsernameSetup?: boolean;
};

export type UserDocument = HydratedDocument<IUser>;

export const User = model<IUser>("User", UserSchema);
